name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Bước 1 - Checkout mã nguồn
      uses: actions/checkout@v4

    # --- PHẦN BỔ SUNG: Dạy robot build ra file .jar trước ---
    - name: Cài đặt JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build dự án bằng Maven
      run: chmod +x mvnw && ./mvnw clean package -DskipTests
    # --------------------------------------------------------

    - name: Bước 2 - Đăng nhập Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Bước 3 - Build và Push Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/demo-spring-boot:latest